### ISSUE TITLE
Menu with navigation

### ISSUE THREAD

**Issue by villivald** [villivald/proj_react_2020#1]
Several pages that would open through the existing dropdown menu

**Comment by adhammo** [comment]
what pages do you want to include in the dropdown menu. and can you assign me to the issue?

**Comment by villivald** [comment]
> what pages do you want to include in the dropdown menu. and can you assign me to the issue?

just some blank pages with placeholders, I mean the main purpose is the implementation of react navigation, I have struggled with it for some reason
