### ISSUE TITLE
Improving the README.md 

### ISSUE THREAD

**Issue by villivald** [villivald/proj_react_2020#5]
Need some fresh ideas for improving Readme.md - styling, stats, any kinds of visual stuff, etc. I am open to all suggestions 🙂. Feel free to make a pull request.

**Comment by ZsuzsaMano** [comment]
Hi, 

I really need to work on my Readme writing skills. So it would be a great project to dive into this topic. Could you assign me, please?

**Comment by abhishekpatel946** [comment]
Hey, @villivald 
I would like to create an awesome README.md for you if you assign it to me.

**Comment by ZsuzsaMano** [comment]
https://blog.bitsrc.io/how-to-write-beautiful-and-meaningful-readme-md-for-your-next-project-897045e3f991

Found this article. I would appreciate any learning resources to create an amazing readme. I decided to really get into this topic now :).

**Comment by ZsuzsaMano** [comment]
Please check the other 2 issues I opened. As I will put images of the site in the readme, it would make sense to first fix those topics if you agree.
